import * as b from 'bobril';

export * from './components/a';
export * from './components/abbreviation';
export * from './components/address';
export * from './components/alert';
export * from './components/blockquote';
export * from './components/bobrilHelpers';
export * from './components/button';
export * from './components/buttonGroup';
export * from './components/buttonToolbar';
export * from './components/checkbox';
export * from './components/cite';
export * from './components/code';
export * from './components/col';
export * from './components/container';
export * from './components/context';
export * from './components/dd';
export * from './components/del';
export * from './components/dl';
export * from './components/dt';
export * from './components/element';
export * from './components/italics';
export * from './components/fieldset';
export * from './components/figure';
export * from './components/footer';
export * from './components/form';
export * from './components/formGroup';
export * from './components/glyphicon';
export * from './components/headings';
export * from './components/helpers';
export * from './components/helpText';
export * from './components/image';
export * from './components/inputCheckbox';
export * from './components/inputGroup';
export * from './components/inputGroupAddon';
export * from './components/inputRadio';
export * from './components/inputText';
export * from './components/ins';
export * from './components/kbd';
export * from './components/label';
export * from './components/li';
export * from './components/ol';
export * from './components/option';
export * from './components/mark';
export * from './components/paragraph';
export * from './components/pre';
export * from './components/radio';
export * from './components/responsive';
export * from './components/responsiveTable';
export * from './components/row';
export * from './components/select';
export * from './components/size';
export * from './components/span';
export * from './components/samp';
export * from './components/small';
export * from './components/strong';
export * from './components/strikethrough';
export * from './components/table';
export * from './components/tbody';
export * from './components/td';
export * from './components/textarea';
export * from './components/th';
export * from './components/thead';
export * from './components/tr';
export * from './components/typography';
export * from './components/ul';
export * from './components/underlined';
export * from './components/validations';
export * from './components/variable';

export function init(): void {
    b.asset('./bootstrap/css/bootstrap.css');
}

export default init;
